apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: api-client-pod
  name: api-client-pod
  namespace: default
spec:
  containers:
  - image: py-httpie
    name: api-client-pod
    imagePullPolicy: Never
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
