apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: py-webserver
  name: py-webserver
  namespace: default
spec:
  containers:
  - image: py-webserver
    name: py-webserver
    imagePullPolicy: Never
    envFrom:
      - configMapRef:
          name: kafka-settings
      - secretRef:
          name: kafka-cred
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
